### ISSUE TITLE
R-HSA-109704: Pathway hasDiagram=True, but no figure relationship

### ISSUE THREAD

**Issue by dvklopfenstein** [reactome/graph-core#1]
Hello,

Thank you very much for Reactome in the graph database format. 

I see that the schemaClass, Pathway for stId:"R-HSA-109704" shows hasDiargam:true, but I do not see a figure relationship to a Figure object.

This is the Neo4j query that I am using:

```
MATCH (p:Pathway{stId:"R-HSA-109704"})-[r]->(dst) RETURN p, r, dst
```

Regards,

DV

**Comment by dvklopfenstein** [comment]
FYI: 789 human pathways have hasDiagram==true, but do not appear to have a png or jpg file associated with it (i.e., no 'figure' relationship to a 'Figure' entity which contains the name of the image file)

**Comment by fabregat** [comment]
Hi DV,

We do not store the images in the graph database, but you can access them via our ContentService. Please check https://reactome.org/ContentService/#/exporter/toRasterUsingGET

Thank you very much for your interest in using Reactome data and software.

I hope it helps!

Best regards,

**Comment by dvklopfenstein** [comment]
FYI: I know there are no diagrams in the Reactome database for neo4j. 

I intended to say "image filenames", not "images" (e.g., the actual image file). 

Many pathways that have diagrams have no associated image filenames in neo4j.

Here is what I see:

```
2,222 Pathways Total for human
  892 Pathways hasDiagram=true
  103 Pathways hasDiagram=true and a have an associated figure filename
  789 Pathways hasDiagram=true have no "figure" relationship or image filename
```

**Comment by fabregat** [comment]
Hi DV,

Figures and diagrams are two different things:

- Figures are illustrations provided by our designers (working together with curators)
- Diagrams are the SBGN-like description of the pathway.

To download the diagrams from the [Content Service](https://reactome.org/ContentService/#/exporter/toRasterUsingGET) please use the StableIdentifier in the link.

Does this answer your question?

**Comment by dvklopfenstein** [comment]
Yes. That definitely answers my confusion. Thank you for your time and attention. Using the Neo4j tools to query the Reactome data is working really well.

**Comment by fabregat** [comment]
We're glad you find the tools useful 👍
