### ISSUE TITLE
Multiple identical copies of CatalystActivity?

### ISSUE THREAD

**Issue by dvklopfenstein** [reactome/graph-core#6]
Hello,

Thank you so much for the great open-data pathway collection. It is extremely helpful. I am working to become familiar with the layout of the Reactome database in neo4j.

Why are there are multiple identical copies of CatalystActivity (except for dbId)? For example, this neo4j command, results in the csv table that is attached. The CatalystActivity instances are identical except for the dbId. I do not see a stId. Is the dbId hardcoded into the CatalystActivity object, or does it change from run-to-run or version-to-version of the Reactome graph database loaded into Neo4j.

MATCH (src:CatalystActivity{displayName:"SUMO transferase activity of UBA2:SAE1 [nucleoplasm]"}) RETURN src

Regards,

DV

Here are the results of the MATCH command:

[export.csv.txt](https://github.com/reactome/graph-core/files/6480436/export.csv.txt)

**Comment by deustp01** [comment]
We'll deal with this via "help", so this ticket can be closed. (I think I do not have permission to close tickets myself, which is fine.)

**Comment by jweiser** [comment]
@deustp01 No problem - I can close it.
